---
- name: install pycrypto
  pip: name=pycrypto state=latest

- name: install pefile
  pip: name=pefile state=latest

- name: install rpyc
  pip: name=rpyc state=latest

- name: install pyyaml
  pip: name=pyyaml state=latest

- name: create dir for source files
  file: path=/home/vagrant/pupy state=directory mode=0755 owner=vagrant group=vagrant

- name: copy pupy rat
  unarchive: src=pupy.tar.gz dest=/home/vagrant/pupy owner=vagrant group=vagrant
