---
- name: copy source
  copy: src=pwnme.c dest=/home/vagrant/pwnme.c owner=vagrant group=vagrant mode=0644

- name: compile pwnme
  shell: gcc -o /bin/pwnme /home/vagrant/pwnme.c

- name: set sticky bit
  file: path=/bin/pwnme mode="u+s,g+s"

